### ISSUE TITLE
ZeroDivisionError: repeated internal nodes

### ISSUE THREAD

**Issue by vrineau** [vrineau/Agatta#1]
A non-explicit ZeroDivisionError occurs due to weight computation when trees in Newick format in the input file contain internal nodes that only refer to a single internal node, such as (a,((b,c)));.

```
 agatta analysis Fichier_arbres_pays.txt --prefix=rslt_dowding --software=paup --softpath=/path/to/paup/paup4a168_ubuntu64 --rosetta=Taxons_pays.csv --replicates=1 --consensus=rcc --analysis=heuristic
                                   Agatta 0.8.1                                    
                       Three-item analysis Python package                       

Starting analysis
Loading character trees
15 characters loaded
Standardising 15 characters
Characters standardised
Managing polymorphism
100%|███████████████████████████████████████████| 15/15 [00:00<00:00, 20.90it/s]
Polymorphism removed: 178 polymorphism free informative subtrees computed
Starting triplet decomposition and FW computation
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/valentin/anaconda3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/site-packages/agatta/analysis.py", line 834, in tripdec_allweights
    FW_node = Fraction(len(taxa_out)*(len(taxa_in)-1), len(taxa_out)*tempw)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/fractions.py", line 157, in __new__
    raise ZeroDivisionError('Fraction(%s, 0)' % numerator)
ZeroDivisionError: Fraction(20, 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/valentin/anaconda3/bin/agatta", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/site-packages/agatta/main.py", line 269, in main
    coremain()
  File "/home/valentin/anaconda3/lib/python3.11/site-packages/agatta/main.py", line 100, in coremain
    agatta_analysis(arguments["<file>"][0],
  File "/home/valentin/anaconda3/lib/python3.11/site-packages/agatta/out.py", line 898, in agatta_analysis
    convert(character_dict,
  File "/home/valentin/anaconda3/lib/python3.11/site-packages/agatta/out.py", line 632, in convert
    triplet_dict = main_tripdec(infile, prefix, taxa_replacement,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/site-packages/agatta/analysis.py", line 1248, in main_tripdec
    triplet_dict = parallel_tripdec(character_dict, weighting,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/site-packages/agatta/analysis.py", line 1070, in parallel_tripdec
    pickle_double = pool.map(func, treetuple)  # list of triplet dict
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/valentin/anaconda3/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
ZeroDivisionError: Fraction(20, 0)

```

An automatic detection of empty nodes should be set up (perhaps also automatically delete these nodes and run the analysis?), and an explicit error specifying the line should be indicated.

**Comment by vrineau** [comment]
Automatic detection and removal of empty nodes added.
